name: ${project.name}
main: ${project.groupId}.${project.artifactId}.Entry
version: ${project.version}
author: ghowden/Eluinhost
database: false
commands:
  flipcrafts:
    permission: uhc.flipcrafts
permissions:
  uhc.flipcrafts:
    default: op